DevFinder/Models/JobPosting.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DevFinder.Models
{
    public class JobPosting
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Company { get; set; }

        [Required]
        public string Location { get; set; }

        public DateTime PostedDate { get; set; } = DateTime.Now;

        public bool IsApproved { get; set; } = false;

        [Required]
        public string UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        public IdentityUser User { get; set; }
    }
}

DevFinder/ViewModels/JobPostingViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DevFinder.ViewModels
{
    public class JobPostingViewModel
    {
        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string Company {  get; set; }

        [Required]
        public string Location { get; set; }
    }
}

DevFinder/Controllers/JobPostingsController.cs
using DevFinder.Constants;
using DevFinder.Models;
using DevFinder.Repositories;
using DevFinder.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DevFinder.Controllers
{
    [Authorize]
    public class JobPostingsController : Controller
    {
        private readonly IRepository<JobPosting> _repository;
        private readonly UserManager<IdentityUser> _userManager;

        public JobPostingsController(IRepository<JobPosting> repository, UserManager<IdentityUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }


        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var AllJobPostings = await _repository.GetAllAsync();
            if (User.IsInRole(Roles.Employer))
            {
                var userId = _userManager.GetUserId(User);
                var filteredJobPostings = AllJobPostings.Where(jobPost => jobPost.UserId == userId);
                return View(filteredJobPostings);
            }
            return View(AllJobPostings);
        }

        [Authorize(Roles = $"{Roles.Admin},{Roles.Employer}")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = $"{Roles.Admin},{Roles.Employer}")]
        public async Task<IActionResult> Create(JobPostingViewModel jobPostingVm)
        {


            if (ModelState.IsValid)
            {
                var jobPosting = new JobPosting
                {
                    Title = jobPostingVm.Title,
                    Description = jobPostingVm.Description,
                    Location = jobPostingVm.Location,
                    Company = jobPostingVm.Company,
                    UserId = _userManager.GetUserId(User)
                };
                await _repository.AddAsync(jobPosting);
                return RedirectToAction(nameof(Index));
            }
            return View(jobPostingVm);
        }

        [HttpDelete]
        [Authorize(Roles = $"{Roles.Admin},{Roles.Employer}")]
        public async Task<IActionResult> Delete(int id)
        {
            var jobPosting = await _repository.GetByIdAsync(id);
            if (jobPosting == null)
            {
                return NotFound();
            }
            var userId = _userManager.GetUserId(User);
            if (User.IsInRole(Roles.Admin) == false && jobPosting.UserId != userId)
            {
                return Forbid();
            }
            await _repository.DeleteAsync(id);

            return Ok();
        }

        //[Authorize(Roles = $"{Roles.Admin},{Roles.Employer}")]
        //public async Task<IActionResult> DeleteEasy(int id)
        //{
        //    var jobPosting = await _repository.GetByIdAsync(id);
        //    if (jobPosting == null)
        //    {
        //        return NotFound();
        //    }
        //    var userId = _userManager.GetUserId(User);
        //    if (User.IsInRole(Roles.Admin) == false && jobPosting.UserId != userId)
        //    {
        //        return Forbid();
        //    }
        //    await _repository.DeleteAsync(id);

        //    return RedirectToAction(nameof(Index));
        //}
    }
}

DevFinder/Views/JobPostings/Create.cshtml
@model DevFinder.ViewModels.JobPostingViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Create</h1>


<form method="post" action="Create">
    <div class="mb-3">
        <label asp-for="Title" class="form-label"></label>
        <input type="text" asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <textarea type="text" asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Company" class="form-label"></label>
        <input type="text" asp-for="Company" class="form-control" />
        <span asp-validation-for="Company" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Location" class="form-label"></label>
        <input type="text" asp-for="Location" class="form-control" />
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>


@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DevFinder/Views/JobPostings/Index.cshtml
@using DevFinder.Constants;
@model IEnumerable<JobPosting>

@{
}
@if(User.IsInRole(Roles.Employer)){
    <h1 class="text-center m-5">Your current job openings</h1>
}else{
    <h1 class="text-center m-5">All open jobs</h1>
}


<div class="list-group">

    @foreach(var jobPosting in Model){
        <div class="list-group-item" id="job-posting-@jobPosting.Id">
            <h3>@jobPosting.Title</h3>
            <p>@jobPosting.Description</p>
            <p><strong>Company:</strong> @jobPosting.Company</p>
            <p><strong>Location:</strong> @jobPosting.Location</p>
            <p><strong>Posted date:</strong> @jobPosting.PostedDate.ToShortDateString()</p>
            @if(User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Employer)){
                <div>
                    <button onclick="deleteJobPosting(@jobPosting.Id)" class="btn btn-sm btn-danger">Delete</button>
                </div>
            }
            @* <a asp-action="DeleteEasy" asp-route-id="@jobPosting.Id" asp-controller="JobPostings">Delete</a> *@
        </div>
    }

</div>

@section Scripts{
    <script>
        function deleteJobPosting(id){
            if(confirm("Are you sure you want to delete this job posting?")){
                //url
                //type (delete)
                //success statement => visually rmove the job posting li
                //error => show an error message

                $.ajax({
                    url: "@Url.Action("Delete","JobPostings")/" + id,
                    type: "delete",
                    success: function(result){
                        $("#job-posting-" + id).remove();
                    },
                    error: function(err){
                        alert("An Error Occurred: " + err);
                    }
                });
            }
        }
    </script>
}